export const copy = {
  ru: {
    breathLabels: { inhale: "Вдох", hold: "Задержка", exhale: "Выдох", rest: "Пауза" },
    obstacleLabel: "Что мешает спать",
    tonight: {
      stress: "Сегодня: дыхание с длинным выдохом, чтобы отпустить напряжение.",
      noise: "Сегодня: фон плотнее, чтобы заглушить город.",
      thoughts: "Сегодня: дыхание квадратом со счётом, чтобы мыслям стало тише.",
    },
    morningEyebrow: "ДОБРОЕ УТРО",
    morningTitle: "За ночь твой хутор подрос.",
    morningNote: "Новое место: {place}. Коснись его на карте, чтобы услышать.",
    sleepQuestion: "Как спалось?",
    moods: ["Беспокойно", "Нормально", "Хорошо"],
    moodThanks: "Спасибо. Так проще понять, какие вечера тебе подходят.",
    morningGo: "Заглянуть в хутор",
    pendingCaption: "Вечер засчитан. Утром здесь появится {place}.",
    pendingBadge: "Утром: {place}",
    earnedNote: "Вечер засчитан. Утром хутор подрастёт.",
    lengthLabel: "Длина вечера",
    lengths: { full: "22 минуты", short: "10 минут" },
    lengthHints: { full: "Дыхание, история и тихий сон", short: "Сразу история, без долгой практики" },
    skipBreath: "Сразу к истории",
    loadingAudio: "Загружаю запись…",
    soundCredits: "Записи и авторы",
    narrationPending: "История текстом и звуки природы · озвучка готовится",
    tag: "Твой цифровой хутор спокойствия",
    welcome: "Место, где можно выдохнуть.",
    intro:
      "Оставь шум дня за лесом. Здесь не нужно спешить — только слушать, отдыхать и понемногу строить свой хутор.",
    enter: "Найти свой покой",
    next: "Продолжить",
    back: "Назад",
    language: "На каком языке тебе уютнее?",
    languageNote: "Его всегда можно изменить в настройках.",
    setup: "Пусть здесь будет по-твоему",
    setupNote: "Два маленьких вопроса перед дорогой.",
    q1: "Что мешает тебе спать?",
    q2: "Какой звук тебя расслабляет?",
    obstacles: ["Стресс", "Шум города", "Мысли"],
    sounds: ["Дождь", "Лес", "Костёр"],
    finish: "Войти в хутор",
    village: "Хутор",
    seasons: ["Первые вечера", "Осень на хуторе"],
    soundsEyebrow: "Звуки",
    profileEyebrow: "Твой покой",
    artCaption: "VЁSKA · БЕЛАРУСЬ",
    coords: "53° с. ш. · 28° в. д.",
    soundTab: "Звуки",
    profile: "Покой",
    evening: "ТВОЁ ТИХОЕ МЕСТО",
    greeting: "Добро пожаловать домой.",
    villageNote: "Каждый вечер покоя оставляет здесь свой свет.",
    level: "День",
    allOpen: "Хутор готов к зиме",
    unlocked: "открыто",
    objects: ["Дом", "Мельница", "Амбар", "Кострище",
      "Сад",
      "Колодец",
      "Баня",
      "Пристань",
      "Пасека",
    ],
    objectNotes: [
      "Дождь по крыше",
      "Ветер в крыльях",
      "Ночной лес",
      "Треск поленьев",
      "Шелест яблонь",
      "Капли у колодца",
      "Треск печи",
      "Ночной ветер над водой",
      "Тихий луг",
    ],
    chapter: "ИСТОРИЯ НА ЭТОТ ВЕЧЕР",
    chapters: [
      "Первый свет",
      "Старая мельница",
      "Тихие сокровища",
      "Тепло, которое остаётся",
      "Яблоки в траве",
      "Глубокая вода",
      "Тёплые камни",
      "Лодка у берега",
      "Спящие ульи",
    ],
    chapterNotes: [
      "Найди тропинку сквозь туман и зажги свет в своём первом доме.",
      "Прислушайся к ветру и разбуди крылья старой мельницы.",
      "Пройди по лесной тропе к амбару, хранящему летнее тепло.",
      "Собери сухие ветки и согрей свой хутор у костра.",
      "Пройди через осенний сад, где яблоки зреют без спешки.",
      "Опусти ведро в старый колодец и послушай глубокую воду.",
      "Согрейся в маленькой бане, пока за окном холодная ночь.",
      "Спустись к озеру, где лодка ждёт у мостков до утра.",
      "Навести спящие ульи и подготовь хутор к зиме.",
    ],
    start: "Начать сеанс",
    duration: "22 минуты",
    headphones: "Лучше слушать в наушниках",
    mapEmpty: "Твой дом ждёт. Первая история откроет старую мельницу.",
    mapHint: "Коснись открытой постройки, чтобы услышать её звук.",
    locked: "Откроется в день",
    all: "Твой хутор наполнен светом. Возвращайся к любимым историям.",
    mixTitle: "У каждого покоя свой звук.",
    mixNote: "Собери вечер, который подходит именно тебе.",
    soundNames: [
      "Дождь за окном",
      "Треск костра",
      "Ночные сверчки",
      "Мягкий ветер и совы",
      "Ветер у мельницы",
      "Тихий скрип мельницы",
    ],
    soundNotes: [
      "Капли на крыше, тишина у озера",
      "Мягкое потрескивание тёплых поленьев",
      "Шорох листвы и ночные насекомые",
      "Медленное дыхание лугов",
      "Глубокий ночной ветер без сов",
      "Ритм деревянных шестерёнок",
    ],
    mixSleep: "Засыпать под этот микс",
    active: "звуков включено",
    stop: "Остановить звуки",
    noSound: "Включи хотя бы один звук с громкостью выше нуля.",
    audioError:
      "Не удалось включить звук. Попробуй нажать ещё раз или открыть приложение в другом браузере.",
    profileTitle: "Тише внутри. Светлее вокруг.",
    profileNote: "Маленькие вечера складываются в большую привычку.",
    evenings: ["вечер на хуторе", "вечера на хуторе", "вечеров на хуторе"],
    minutesLabel: ["минута покоя", "минуты покоя", "минут покоя"],
    achievements: "Твой хутор растёт",
    settings: "Как тебе удобно",
    langLabel: "Язык приложения",
    voice: "Голос рассказчика",
    voiceNote: "Озвучка · elevenlabs.io",
    subscription: "Подписка",
    soon: "Появится позже",
    feedback: "Написать создателю",
    local:
      "Твой прогресс хранится только в этом браузере. Очистка данных сайта удалит его.",
    pause: "Пауза",
    resume: "Продолжить",
    exit: "Завершить сеанс",
    exitNote: "Вечер засчитывается, когда история дослушана. Уже сохранённый прогресс останется.",
    stay: "Остаться",
    leave: "Выйти",
    session: "СЕАНС СПОКОЙСТВИЯ",
    breathe: "Вдох. Медленный выдох.",
    choice: "Коснись света, когда будешь готов.",
    fog: "Проведи в сторону или коснись, чтобы развеять туман",
    fogDone: "Туман расступается",
    light: "Зажечь фонарь",
    lightDone: "Фонарь освещает твою дорогу",
    completed: "Ещё немного света в твоём хуторе.",
    completedNote: "История завершена. Теперь можно просто уснуть.",
    sleep: "Перейти ко сну",
    home: "Вернуться в хутор",
    sleepTitle: "Пусть всё подождёт.",
    sleepSub: "Ты уже дома.",
    timer: "Таймер сна",
    min: "мин",
    infinity: "Без конца",
    sleepEnd: "Тихой ночи.",
    sleepEndNote: "Звуки плавно затихли.",
    storageError:
      "Браузер не разрешает сохранять прогресс. Он останется доступен до закрытия страницы.",
    narrationMissing: "Голос недоступен: история остаётся на экране.",
    readiness: "ТВОЙ ПЕРВЫЙ ВЕЧЕР",
    privacy: "Без аккаунта. Без суеты.",
    return: "Назад",
    replay: "Слушать снова",
    synthetic: "Живые записи природы, мягко соединённые в петли.",
    sleepLimit:
      "На некоторых телефонах звук может остановиться при блокировке экрана.",
    voiceUnavailable: "Озвучка ElevenLabs ещё не добавлена.",
  },
  en: {
    breathLabels: { inhale: "Inhale", hold: "Hold", exhale: "Exhale", rest: "Rest" },
    obstacleLabel: "What keeps you awake",
    tonight: {
      stress: "Tonight: breathing with a longer exhale, to let tension go.",
      noise: "Tonight: a fuller soundscape to mask the city.",
      thoughts: "Tonight: box breathing with a count, so thoughts grow quieter.",
    },
    morningEyebrow: "GOOD MORNING",
    morningTitle: "Your village grew overnight.",
    morningNote: "A new place: {place}. Tap it on the map to hear it.",
    sleepQuestion: "How did you sleep?",
    moods: ["Restless", "Okay", "Well"],
    moodThanks: "Thank you. It helps to see which evenings suit you.",
    morningGo: "Visit the village",
    pendingCaption: "Evening counted. {place} will appear here in the morning.",
    pendingBadge: "Morning: {place}",
    earnedNote: "Evening counted. Your village will grow by morning.",
    lengthLabel: "Evening length",
    lengths: { full: "22 minutes", short: "10 minutes" },
    lengthHints: { full: "Breathing, a story and quiet sleep", short: "Straight to the story, no long practice" },
    skipBreath: "Skip to the story",
    loadingAudio: "Loading recording…",
    soundCredits: "Recordings and credits",
    narrationPending: "Written story and nature sounds · narration coming soon",
    tag: "Your digital village of peace",
    welcome: "A place to breathe out.",
    intro:
      "Leave the noise of the day beyond the forest. There is no hurry here. Just listen, rest, and slowly grow your own village.",
    enter: "Find your quiet",
    next: "Continue",
    back: "Back",
    language: "Which language feels like home?",
    languageNote: "You can always change it in settings.",
    setup: "Make this place your own",
    setupNote: "Two small questions before we begin.",
    q1: "What keeps you awake?",
    q2: "Which sound helps you relax?",
    obstacles: ["Stress", "City noise", "Thoughts"],
    sounds: ["Rain", "Forest", "Bonfire"],
    finish: "Enter the village",
    village: "The Village",
    seasons: ["First evenings", "Autumn in the village"],
    soundsEyebrow: "Soundscapes",
    profileEyebrow: "Your peace",
    artCaption: "VЁSKA · BELARUS",
    coords: "53° N · 28° E",
    soundTab: "Sounds",
    profile: "Your Peace",
    evening: "YOUR QUIET PLACE",
    greeting: "Welcome home.",
    villageNote: "Every peaceful evening leaves a little light here.",
    level: "Day",
    allOpen: "Ready for winter",
    unlocked: "unlocked",
    objects: ["The Cottage", "The Mill", "The Barn", "The Bonfire",
      "The Orchard",
      "The Well",
      "The Bathhouse",
      "The Jetty",
      "The Apiary",
    ],
    objectNotes: [
      "Rain on the roof",
      "Wind in the sails",
      "Forest at night",
      "Crackling logs",
      "Rustling apple trees",
      "Drops by the well",
      "A crackling stove",
      "Night wind over the water",
      "A quiet meadow",
    ],
    chapter: "TONIGHT’S STORY",
    chapters: [
      "The first light",
      "The old mill",
      "Quiet treasures",
      "The warmth that stays",
      "Apples in the Grass",
      "Deep Water",
      "Warm Stones",
      "A Boat by the Shore",
      "Sleeping Hives",
    ],
    chapterNotes: [
      "Find a path through the mist and light the windows of your first home.",
      "Listen to the wind and wake the sails of the old mill.",
      "Follow the forest path to a barn that holds the warmth of summer.",
      "Gather dry branches and bring warmth to your village.",
      "Walk through the autumn orchard, where apples ripen without hurry.",
      "Lower a bucket into the old well and listen to the deep water.",
      "Warm up in a small bathhouse while the night outside grows cold.",
      "Walk down to the lake, where a boat waits by the jetty until morning.",
      "Visit the sleeping hives and ready your village for winter.",
    ],
    start: "Start session",
    duration: "22 minutes",
    headphones: "Best enjoyed with headphones",
    mapEmpty: "Your cottage is waiting. The first story opens the old mill.",
    mapHint: "Touch an unlocked place to hear its sound.",
    locked: "Unlocks on day",
    all: "Your village is full of light. Revisit your favourite stories.",
    mixTitle: "Every quiet has its own sound.",
    mixNote: "Create the evening that feels right for you.",
    soundNames: [
      "Rain outside",
      "Crackling fire",
      "Night crickets",
      "Soft wind & owls",
      "Wind by the mill",
      "Quiet wooden gears",
    ],
    soundNotes: [
      "Drops on a rooftop beside the lake",
      "The gentle crackle of warm logs",
      "Rustling leaves and night insects",
      "The slow breathing of the meadows",
      "Deep country wind without owls",
      "A gentle rhythm of wooden gears",
    ],
    mixSleep: "Fall asleep to this mix",
    active: "sounds playing",
    stop: "Stop sounds",
    noSound: "Enable at least one sound with volume above zero.",
    audioError:
      "Audio could not start. Try again or open the app in another browser.",
    profileTitle: "Quieter within. Brighter around.",
    profileNote: "Small evenings become a gentle habit.",
    evenings: ["evening in the village", "evenings in the village"],
    minutesLabel: ["peaceful minute", "peaceful minutes"],
    achievements: "Your village is growing",
    settings: "Make yourself comfortable",
    langLabel: "App language",
    voice: "Story narrator",
    voiceNote: "Narration · elevenlabs.io",
    subscription: "Subscription",
    soon: "Coming later",
    feedback: "Contact the creator",
    local:
      "Your progress stays in this browser. Clearing site data will remove it.",
    pause: "Pause",
    resume: "Resume",
    exit: "End session",
    exitNote: "The evening counts once the story has been heard. Your saved progress stays with you.",
    stay: "Stay",
    leave: "Leave",
    session: "A MOMENT OF PEACE",
    breathe: "Breathe in. Slowly breathe out.",
    choice: "Touch the light when you are ready.",
    fog: "Swipe sideways or tap to clear the mist",
    fogDone: "The mist is lifting",
    light: "Light the lantern",
    lightDone: "The lantern is lighting your way",
    completed: "A little more light in your village.",
    completedNote: "The story is complete. Now you can simply drift off.",
    sleep: "Drift off to sleep",
    home: "Return to the village",
    sleepTitle: "Let everything wait.",
    sleepSub: "You are home.",
    timer: "Sleep timer",
    min: "min",
    infinity: "Forever",
    sleepEnd: "Sleep well.",
    sleepEndNote: "The sounds have gently faded away.",
    storageError:
      "Your browser cannot save progress. It will stay available until you close this page.",
    narrationMissing: "Voice is unavailable. You can still read the story.",
    readiness: "YOUR FIRST EVENING",
    privacy: "No account. No hurry.",
    return: "Back",
    replay: "Listen again",
    synthetic: "Real nature recordings with gently blended loops.",
    sleepLimit: "Some phones may stop audio when the screen is locked.",
    voiceUnavailable: "ElevenLabs narration has not been added yet.",
  },
};
export const stories = {
  ru: [
    [
      "Представь, что город остался далеко позади. Перед тобой узкая тропинка, а по обе стороны — высокая, прохладная трава. Почувствуй опору под ногами. Тебе больше никуда не нужно спешить. Вдохни спокойно. И позволь выдоху быть чуть длиннее вдоха.",
      "Над землёй поднимается лёгкий туман. Среди деревьев виднеется маленький дом. В ладони у тебя фонарь. Когда захочется, коснись света. Тёплый круг на тропинке станет твоим спутником. Здесь достаточно одного небольшого шага.",
      "Ты подходишь к дому. Деревянная дверь легко открывается. Внутри пахнет сухими травами и тёплым деревом. За окном начинает идти дождь. Каждая капля словно уносит с собой одну заботу. Можно опустить плечи. Можно ничего не решать.",
      "В окнах твоего дома загорается свет. Он останется здесь и завтра. Ты можешь возвращаться сюда столько раз, сколько захочешь. Устройся поудобнее. Прислушайся к дождю. Этот вечер уже принадлежит тебе. Всё остальное подождёт.",
    ],
    [
      "Вечерняя тропинка ведёт тебя к полю. Воздух здесь пахнет травой. Вдалеке стоит старая мельница. Её крылья неподвижны. Ты идёшь медленно и замечаешь, как с каждым шагом дыхание становится спокойнее.",
      "В траве мерцает огонёк. Зажги свой фонарь, если хочешь видеть дорогу яснее. Поле мягко колышется вокруг. Ветер ничего не требует. Он просто приходит и уходит, как твоё дыхание.",
      "Ты останавливаешься возле старой мельницы. Мельник оставляет фонарь у двери и желает тебе тихой ночи. Лёгкий ветер начинает медленно вращать деревянные крылья. Шестерёнки отвечают мягким, неторопливым скрипом. Сегодня больше ничего не нужно заканчивать. Пусть ветер делает свою работу. А ты можешь просто отдохнуть.",
      "Мельница ожила. Её спокойное движение теперь часть твоего хутора. Ветер шепчет в траве, а небо становится глубже. Позволь мыслям проходить мимо. Здесь можно отдохнуть. Здесь достаточно просто быть.",
    ],
    [
      "Сегодня тропинка уходит в лес. Под ногами мягкая хвоя. Среди ветвей видны звёзды. Ты слышишь шелест листьев и далёкое пение ночных насекомых. С каждым шагом мир становится тише.",
      "Между деревьями стоит амбар. В нём хранятся маленькие сокровища лета. Можно зажечь фонарь и рассмотреть потемневшее дерево, узор на двери, сухой лист у порога. У каждой мелочи есть своё место.",
      "Дверь открывается. На полках стоят корзины, связки трав и льняные мешочки. Здесь никто ничего не потеряет. Представь, что и заботы можно на время оставить на одной из полок. Утром ты решишь, нужны ли они тебе.",
      "Амбар теперь часть твоего хутора. За его дверью всё спокойно. Ты выходишь на тропинку, и лес обнимает тебя тишиной. Почувствуй, как тело отдыхает. Сегодня ты уже сделал достаточно.",
    ],
    [
      "Вечер собрал твой хутор под звёздным небом. Светится дом, медленно вращается мельница, отдыхает амбар. На поляне есть место для небольшого костра. Ты приносишь несколько сухих веток.",
      "Можно зажечь фонарь и присесть рядом. Ничего большого сегодня не требуется. Один маленький огонёк. Один спокойный вдох. Ночь вокруг мягкая и дружелюбная.",
      "Пламя поднимается над поленьями. Дерево тихо потрескивает. Ты чувствуешь тепло на ладонях. Смотри, как огонь меняет форму. Мысли тоже могут меняться и исчезать. Тебе не нужно держать их все.",
      "В твоём хуторе появился костёр. Здесь всегда найдётся немного тепла. Ты устроился удобно, день завершён. Пусть звуки медленно отдаляются. Пусть сон приходит тогда, когда захочет. Ты дома.",
    ],
    [
      "Осень пришла на хутор тихо. Воздух стал прохладнее, а трава мягче и темнее. Тропинка ведёт за дом, туда, где растут старые яблони. Ты идёшь не спеша. Под ногами шуршат первые листья.",
      "Между деревьями лежит лёгкий туман. Зажги фонарь, если хочется. Свет ложится на ветви, и в листве видны круглые яблоки. Они никуда не торопятся. Они просто зреют, день за днём.",
      "Под яблоней стоит деревянная скамейка. Где-то рядом падает яблоко и тихо катится в траву. Пахнет сладко и немного холодно. Ветер едва трогает листья. Сегодня можно ничего не собирать. Сад справится сам. Достаточно просто сидеть и дышать.",
      "Сад теперь часть твоего хутора. Яблони будут стоять здесь и завтра. Плечи становятся тяжёлыми и тёплыми. Пусть веки тоже отдыхают. Осень бережёт тебя.",
    ],
    [
      "Сегодня тропинка ведёт к краю двора. Там, где кончается трава, стоит старый колодец. Над ним деревянная крыша и ворот с толстой верёвкой. Вечер тихий. Слышно, как где-то капает вода.",
      "Туман стелется у самой земли. Зажги фонарь и подойди ближе. Свет падает на мокрые камни. Внизу темно и спокойно. Глубокая вода хранит прохладу всего лета.",
      "Ведро медленно опускается вниз. Ворот поскрипывает, верёвка разматывается виток за витком. Где-то внизу вода тихо принимает ведро. Подожди немного. Поднимай не спеша. Холодная вода блестит в свете фонаря. Один глоток, и внутри становится чище.",
      "Колодец теперь часть твоего хутора. Его вода всегда будет здесь, глубоко и спокойно. Дыхание становится таким же ровным. Мысли опускаются вниз, как ведро на верёвке. И становятся тише.",
    ],
    [
      "Ночь стала прохладной, и пальцам хочется тепла. За садом, у самой тропинки, стоит маленькая баня. Из трубы поднимается тонкий дымок. Окошко светится жёлтым.",
      "Над травой ещё держится туман. Зажги фонарь, чтобы видеть ступеньки. Дверь тяжёлая, деревянная. Внутри пахнет берёзовыми вениками и тёплым деревом.",
      "Вдоль стены стоит широкая лавка. Камни в печи дышат теплом. Тепло медленно входит в ладони, потом в плечи, потом в спину. Мышцы одна за другой отпускают день. Здесь не нужно ничего делать. Только сидеть и согреваться. Капля воды шипит на камнях и становится мягким паром.",
      "Баня теперь часть твоего хутора. Тепло останется с тобой, даже когда выйдешь в ночь. Тело тяжёлое и спокойное. Дыши медленно. Самое время засыпать.",
    ],
    [
      "Сегодня тропинка спускается к озеру. Вода лежит неподвижно, как тёмное стекло. У берега деревянные мостки, а рядом покачивается старая лодка. Где-то в камышах вскрикивает ночная птица.",
      "Над водой поднимается туман. Зажги фонарь. Его отражение дрожит на поверхности озера. Доски мостков чуть влажные и прохладные. Можно пройти до самого края.",
      "На краю мостков можно сесть и опустить ноги над водой. Лодка тихо стукается бортом о сваю. Вода отвечает ей мягким плеском. Звёзды опускаются в озеро одна за другой. Небо и вода становятся одним целым. Не нужно никуда плыть. Лодка подождёт до утра.",
      "Пристань теперь часть твоего хутора. Озеро будет здесь, тихое и глубокое. Позволь мыслям отплыть от берега. Пусть они уходят в туман. А ты остаёшься здесь, в покое.",
    ],
    [
      "Это последний вечер осени на хуторе. Тропинка ведёт на край луга, к старым липам. Под ними стоят деревянные ульи с выцветшей краской. Вокруг очень тихо.",
      "Туман укрывает луг, как одеяло. Зажги фонарь и подойди поближе, без спешки. Пчёлы уже не летают. Они собрались внутри, тесно и тепло, чтобы вместе переждать холода.",
      "Стенка улья тёплая, к ней можно прислониться. Изнутри доносится едва слышное гудение. Оно ровное, как дыхание большого спокойного существа. Пчёлы не спешат. Всё лето они работали, а теперь отдыхают. Мёда им хватит до самой весны. И тебе хватит сил на завтра.",
      "Пасека теперь часть твоего хутора. Хутор готов к зиме. Всё на своих местах: дом, мельница, сад и колодец. Можно закрыть глаза. Ты дома.",
    ],
  ],
  en: [
    [
      "Imagine the city far behind you. A narrow path stretches ahead, with cool, tall grass on either side. Feel the ground supporting you. There is nowhere else you need to be. Breathe in gently. Let the breath out be a little longer.",
      "A light mist rises from the earth. Between the trees, a small cottage comes into view. There is a lantern in your hand. Touch its light whenever you wish. A warm circle on the path will keep you company. One small step is enough.",
      "You reach the cottage. The wooden door opens easily. Inside, it smells of dried herbs and warm timber. Rain begins to fall outside. Imagine each drop carrying away one small worry. Let your shoulders soften. There is nothing to solve.",
      "A light comes on in your cottage windows. It will still be here tomorrow. You can return as often as you like. Make yourself comfortable. Listen to the rain. This evening belongs to you. Everything else can wait.",
    ],
    [
      "The evening path leads into a meadow. The air smells of grass. An old mill stands in the distance, its sails still. Walk slowly. Notice how your breathing softens with every step.",
      "A tiny light glimmers in the grass. Light your lantern if you wish. The meadow sways around you. The wind asks for nothing. It simply comes and goes, like your breath.",
      "You stop beside the old mill. The miller leaves a lantern by the door and wishes you a quiet night. A gentle breeze sets the wooden sails in motion. The gears answer with a soft, unhurried creak. Nothing needs to be finished tonight. Let the wind do its work. You can simply rest.",
      "The mill is awake. Its gentle movement is now part of your village. Wind whispers in the grass as the sky deepens. Let thoughts drift past. You can rest here. Simply being here is enough.",
    ],
    [
      "Tonight the path leads into the forest. Soft pine needles lie beneath your feet. Stars shine between the branches. Leaves rustle and night insects sing. With every step, the world grows quieter.",
      "A small barn stands between the trees. It holds the treasures of summer. Light your lantern and notice the old wood, the pattern on the door, a dry leaf on the step. Every small thing has a place.",
      "The door opens. Shelves hold baskets, dried herbs and linen bags. Nothing needs to be lost here. Imagine leaving your worries on one of the shelves for tonight. In the morning, you can decide whether you need them.",
      "The barn is now part of your village. All is quiet behind its door. You return to the path and the forest wraps you in stillness. Feel your body resting. You have done enough for today.",
    ],
    [
      "Evening gathers your village beneath the stars. The cottage glows, the mill turns slowly and the barn rests. There is space in the clearing for a small bonfire. You bring a few dry branches.",
      "Light your lantern and sit nearby. Nothing big is needed tonight. One small flame. One peaceful breath. The night around you is gentle and welcoming.",
      "Flames rise above the logs. The wood crackles softly. You feel warmth on your palms. Watch the fire change shape. Thoughts can change and disappear too. You do not have to hold them all.",
      "There is a bonfire in your village now. A little warmth will always be waiting here. You are comfortable. The day is done. Let the sounds slowly drift away. Let sleep arrive in its own time. You are home.",
    ],
    [
      "Autumn has come quietly to the village. The air is cooler now, and the grass is softer and darker. The path leads behind the cottage, to the old apple trees. Walk without hurry. The first leaves rustle under your feet.",
      "A light mist lies between the trees. Light your lantern if you wish. The light falls on the branches, and round apples show among the leaves. They are in no hurry. They simply ripen, day after day.",
      "A wooden bench stands beneath an apple tree. Somewhere nearby an apple falls and rolls softly into the grass. The air smells sweet and a little cold. The wind barely touches the leaves. Nothing needs to be gathered tonight. The orchard will manage on its own. It is enough to sit and breathe.",
      "The orchard is now part of your village. The apple trees will still be here tomorrow. Your shoulders grow heavy and warm. Let your eyelids rest too. Autumn is looking after you.",
    ],
    [
      "Tonight the path leads to the edge of the yard. Where the grass ends, there is an old well. Above it is a small wooden roof and a winch with a thick rope. The evening is quiet. Somewhere, water is dripping.",
      "Mist creeps close to the ground. Light your lantern and come closer. The light falls on wet stones. Down below it is dark and calm. The deep water keeps the coolness of the whole summer.",
      "The bucket slowly goes down. The winch creaks softly as the rope unwinds, turn after turn. Somewhere below, the water quietly takes the bucket. Wait a moment. Lift it without hurry. Cold water glimmers in the lantern light. One sip, and everything inside feels clearer.",
      "The well is now part of your village. Its water will always be here, deep and still. Your breathing becomes just as even. Thoughts sink down, like a bucket on a rope. And grow quieter.",
    ],
    [
      "The night has turned cool, and your fingers want warmth. Past the orchard, right by the path, stands a small bathhouse. A thin thread of smoke rises from the chimney. The little window glows yellow.",
      "Mist still lingers over the grass. Light your lantern to see the steps. The door is heavy and wooden. Inside it smells of birch leaves and warm timber.",
      "A wide bench runs along the wall. The stones in the stove breathe out warmth. Warmth slowly moves into your hands, then your shoulders, then your back. One by one, your muscles let go of the day. There is nothing to do here. Only sit and grow warm. A drop of water hisses on the stones and turns into soft steam.",
      "The bathhouse is now part of your village. The warmth will stay with you, even out in the night. Your body is heavy and calm. Breathe slowly. It is time to sleep.",
    ],
    [
      "Tonight the path goes down to the lake. The water lies still, like dark glass. There is a wooden jetty by the shore, and an old boat rocks gently beside it. Somewhere in the reeds, a night bird calls.",
      "Mist rises over the water. Light your lantern. Its reflection trembles on the surface of the lake. The jetty boards are a little damp and cool. You can walk all the way to the end.",
      "At the end of the jetty you can sit with your feet above the water. The boat knocks softly against a post. The water answers with a gentle splash. One by one, the stars sink into the lake. Sky and water become one. There is nowhere to sail. The boat will wait until morning.",
      "The jetty is now part of your village. The lake will stay here, quiet and deep. Let your thoughts drift away from the shore. Let them go into the mist. And you stay here, at peace.",
    ],
    [
      "This is the last autumn evening in the village. The path leads to the edge of the meadow, to the old linden trees. Beneath them stand wooden hives with faded paint. Everything is very quiet.",
      "Mist covers the meadow like a blanket. Light your lantern and come closer, without hurry. The bees no longer fly. They have gathered inside, close and warm, to wait out the cold together.",
      "The side of the hive is warm enough to lean against. From inside comes a faint, steady hum. It is even, like the breathing of a large and peaceful creature. The bees are in no hurry. All summer they worked, and now they rest. Their honey will last until spring. And you will have strength enough for tomorrow.",
      "The apiary is now part of your village. Your village is ready for winter. Everything is in its place: the cottage, the mill, the orchard and the well. You can close your eyes. You are home.",
    ],
  ],
};
